-- Two columns for the deal workspace rework (icm-board decisions D24–D26,
-- 2026-09-22), both purely additive and both reversible by dropping them.
--
-- `support_minor` — the monthly support line beside a one-off ("one-off +
-- support": crash fixes on call for a build with state). Not a retainer, which
-- stays `billing_type = 'monthly'` on `value_minor`. Defaults to 0 (none), so
-- every existing row means exactly what it meant before this ran, and the
-- leads list's "/ month" total simply gains the column for active rows.
--
-- `deal_slug` — which folder under icm-board's `workspaces/deals/` holds this
-- relationship's documents. One home per fact: the row is the state, the
-- folder is the words, and the dashboard reads the folder live over the
-- GitHub API. Nullable (most rows predate the folders) and unique when set —
-- one folder is one relationship, never two. Generated by drizzle-kit; the
-- ten existing folder names are set on their rows by hand from the deal card
-- after this applies (the mapping is in the PR body).
ALTER TABLE "biz"."clients" ADD COLUMN "support_minor" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "biz"."clients" ADD COLUMN "deal_slug" varchar(80);--> statement-breakpoint
ALTER TABLE "biz"."clients" ADD CONSTRAINT "clients_deal_slug_unique" UNIQUE("deal_slug");