-- Drops `deal_slug`, one day after 0024 added it (icm-board decision D28,
-- 2026-09-23). The deal folder under icm-board's `workspaces/deals/` is now
-- *named after the delivery repo* — `<repo name>/`, the name half of
-- `github_repo` — so the column was the same fact in a second home, the mirror
-- D24 exists to forbid. The dashboard derives the folder (`lib/deals.ts`,
-- `dealFolderSlug`) and never stores it. The one value set by hand before this
-- ran is derivable from that row's repo and is not migrated. Generated by
-- drizzle-kit; reversible only by re-adding the column (0024's shape).
ALTER TABLE "biz"."clients" DROP CONSTRAINT "clients_deal_slug_unique";--> statement-breakpoint
ALTER TABLE "biz"."clients" DROP COLUMN "deal_slug";