-- Drops the todo list and the compliance calendar (admin-cockpit-redesign
-- D-16, 2026-09-25). Todos live in Google Tasks, and neither table was read
-- any more; the rows go with them, unexported, by the operator's decision.
-- Nothing references either table (`tasks.client_id` points out, not in), so
-- CASCADE drops only their own constraints. Generated by drizzle-kit;
-- forward-only — the previous admin code reads both tables and must not be
-- redeployed against this schema.
DROP TABLE "biz"."compliance_dates" CASCADE;--> statement-breakpoint
DROP TABLE "biz"."tasks" CASCADE;