// Barrel — the one import surface for consumers: `@jamie-nisbet/services`.
export { db, getDb } from "./client"
export * from "./schema"
export * from "./queries/clients"
export * from "./queries/compliance"
export * from "./queries/deals"
export * from "./queries/documents"
export * from "./queries/generations"
export * from "./queries/tasks"
export * from "./queries/workshop"
